version: 1

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=1
    goos:
      - darwin

    main: ./cmd/plummet

release:
  github:
    owner: Hillside-Labs
    name: plummet

  prerelease: auto

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
